export const errorListTest = [
    {
        code: 'E1012',
        finished: '2024-09-03T17:44:42.538304',
        id: 'oKn0OF5z7YZ',
        status: 'Error',
        message:
            'Could not find DataElement: `MetadataIdentifier(idScheme=UID, identifier=testOrg, attributeValue=null)`, linked to Event.',
        user: 'GOLswS44mh8',
        args: [
            'MetadataIdentifier(idScheme=UID, identifier=testOrg, attributeValue=null)',
        ],
        dataElement: 'fbfJHSPpUQD',
        enrollment: '',
        event: '',
        jobId: 'zlEKs5yhSR4',
        orgUnit: 'y77LiPqLMoq',
        program: 'lxAQ7Zs9VYR',
        programStage: 'dBwrot7S420',
        tea: '',
        tei: '',
        type: 'EVENT',
    },
    {
        code: 'E1011',
        finished: '2024-09-02T17:44:42.538304',
        id: 'oKn0OF5z7Yl',
        status: 'Info',
        message:
            'Could not find OrganisationUnit: `MetadataIdentifier(idScheme=UID, identifier=testOrg, attributeValue=null)`, linked to Event.',
        user: 'GOLswS44mh8',
        args: [
            'MetadataIdentifier(idScheme=UID, identifier=testOrg, attributeValue=null)',
        ],
        dataElement: 'fbfJHSPpUQD',
        enrollment: '',
        event: '',
        jobId: 'zlEKs5yhSR4',
        orgUnit: 'y77LiPqLMoq',
        program: 'lxAQ7Zs9VYR',
        programStage: 'dBwrot7S420',
        tea: '',
        tei: '',
        type: 'EVENT',
    },
    {
        code: 'E1011',
        finished: '2024-09-05T17:44:42.538304',
        id: 'oKn0OF5z7Y8',
        status: 'Error',
        message:
            'Could not find OrganisationUnit: `MetadataIdentifier(idScheme=UID, identifier=testOrg, attributeValue=null)`, linked to Event.',
        user: 'GOLswS44mh8',
        args: [
            'MetadataIdentifier(idScheme=UID, identifier=testOrg, attributeValue=null)',
        ],
        dataElement: '',
        enrollment: '',
        event: '',
        jobId: 'zlEKs5yhSR3',
        orgUnit: '',
        program: 'IpHINAT79UW',
        programStage: 'A03MvHHogjR',
        tea: 'w75KJ2mc4zz',
        tei: '',
        type: 'EVENT',
    },
    {
        code: 'E1014',
        finished: '2024-09-04T17:44:42.538304',
        id: 'oKn0OF5z7YW',
        status: 'Info',
        message:
            'Wrong valueType `MetadataIdentifier(idScheme=UID, identifier=testOrg, attributeValue=null)`, linked to Event.',
        user: 'GOLswS44mh8',
        args: [
            'MetadataIdentifier(idScheme=UID, identifier=testOrg, attributeValue=null)',
        ],
        dataElement: '',
        enrollment: '',
        event: '',
        jobId: 'zlEKs5yhSR3',
        orgUnit: '',
        program: 'IpHINAT79UW',
        programStage: 'A03MvHHogjR',
        tea: 'w75KJ2mc4zz',
        tei: '',
        type: 'EVENT',
    },
    {
        code: 'E1014',
        finished: '2024-09-06T17:44:42.538304',
        id: 'oKn0OF5z7Y9',
        status: 'Error',
        message:
            'Wrong valueType: `MetadataIdentifier(idScheme=UID, identifier=testOrg, attributeValue=null)`, linked to Event.',
        user: 'GOLswS44mh8',
        args: [
            'MetadataIdentifier(idScheme=UID, identifier=testOrg, attributeValue=null)',
        ],
        dataElement: '',
        enrollment: '',
        event: '',
        jobId: 'zlEKs5yhSR3',
        orgUnit: '',
        program: 'IpHINAT79UW',
        programStage: 'A03MvHHogjR',
        tea: 'w75KJ2mc4zz',
        tei: '',
        type: 'EVENT',
    },
]
