export const jobErrors = [
    {
        args: ['HLmTEmupdX0', 'value_not_bool'],
        code: 'E1302',
        dataElement: '',
        enrollment: '',
        event: '',
        finished: '2024-09-02T17:44:42.538304',
        id: 'c0tuHs0y901',
        jobId: 'zlEKs5yhSR4',
        message: 'DataElement `HLmTEmupdX0` is not valid: `value_not_bool`',
        orgUnit: '',
        program: undefined,
        programStage: undefined,
        status: 'Error',
        tea: '',
        tei: '',
        type: 'EVENT',
        user: 'GOLswS44mh8',
    },
    {
        args: [
            'MetadataIdentifier(idScheme=UID, identifier=testOrg, attributeValue=null)',
        ],
        code: 'E1011',
        dataElement: '',
        enrollment: '',
        event: '',
        finished: '2024-09-02T17:44:42.538304',
        id: 'oKn0OF5z7Yl',
        jobId: 'zlEKs5yhSR4',
        message:
            'Could not find OrganisationUnit: `MetadataIdentifier(idScheme=UID, identifier=testOrg, attributeValue=null)`, linked to Event.',
        orgUnit: '',
        program: undefined,
        programStage: undefined,
        status: 'Error',
        tea: '',
        tei: '',
        type: 'EVENT',
        user: 'GOLswS44mh8',
    },
]
